# Generated by Django 5.2.8 on 2025-11-14 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0003_orderitem_alter_order_options_remove_order_items_and_more'),
    ]

    operations = [
    ]
