# Generated by Django 5.2.8 on 2025-11-14 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0004_auto_20251114_1359'),
    ]

    operations = [
    ]
