# Generated by Django 5.2.8 on 2025-11-14 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0005_auto_20251114_1419'),
    ]

    operations = [
    ]
