# Generated by Django 5.2.8 on 2025-11-17 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0007_order_waiter_orderitem_food_id'),
        ('management', '0007_fooditem_auto_manage_stock_fooditem_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='food_id',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='FoodItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.fooditem'),
        ),
    ]
