# Generated by Django 5.2.8 on 2025-11-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0008_remove_orderitem_food_id_orderitem_fooditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='FoodItem',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='food_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
