# Generated by Django 5.2.8 on 2025-11-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0010_order_is_refunded_order_refund_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='selected_seats',
            field=models.JSONField(blank=True, default=list, help_text='List of selected seat numbers'),
        ),
        migrations.AddField(
            model_name='order',
            name='table_id',
            field=models.IntegerField(blank=True, help_text='Reference to RestaurantTable', null=True),
        ),
    ]
