# Generated by Django 5.2.8 on 2025-11-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='adminuser_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='adminuser_perms', to='auth.permission'),
        ),
    ]
