# Generated by Django 5.2.8 on 2025-11-12 08:27

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_emailotp_adminuser_is_verified_alter_adminuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('food', 'Food'), ('cafe', 'Cafe')], default='food', max_length=10)),
                ('subcategory', models.CharField(blank=True, choices=[('tiffin', 'Tiffin'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('breakfast', 'Breakfast'), ('snacks', 'Snacks'), ('beverages', 'Beverages'), ('desserts', 'Desserts')], max_length=20, null=True)),
                ('food_type', models.CharField(choices=[('veg', 'Veg'), ('nonveg', 'Non-Veg'), ('egg', 'Egg')], default='veg', max_length=10)),
                ('food_name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
