# Generated by Django 5.2.8 on 2025-11-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_restauranttable'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('subcategory_id', models.AutoField(primary_key=True, serialize=False)),
                ('subcategory_name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Sub Categories',
                'db_table': 'subcategories',
                'ordering': ['subcategory_name'],
            },
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
