# Generated by Django 5.2.8 on 2025-11-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_fooditem_auto_manage_stock_fooditem_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restauranttable',
            name='occupied_seats',
            field=models.PositiveIntegerField(default=0, help_text='Currently occupied seats'),
        ),
        migrations.AddField(
            model_name='restauranttable',
            name='seats',
            field=models.PositiveIntegerField(default=4, help_text='Total seats at this table'),
        ),
    ]
