# Generated by Django 5.2.8 on 2025-11-19 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_fooditem_auto_manage_stock_fooditem_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restauranttable',
            name='seats_per_row',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='restauranttable',
            name='total_seats',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.CreateModel(
            name='TableSeat',
            fields=[
                ('seat_id', models.AutoField(primary_key=True, serialize=False)),
                ('seat_number', models.CharField(max_length=10)),
                ('row_number', models.PositiveIntegerField()),
                ('seat_label', models.CharField(max_length=5)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='management.restauranttable')),
            ],
            options={
                'db_table': 'table_seats',
                'ordering': ['row_number', 'seat_label'],
                'unique_together': {('table', 'seat_number')},
            },
        ),
    ]
