# Generated by Django 5.2.8 on 2025-11-18 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_restauranttable_occupied_seats_restauranttable_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restauranttable',
            name='occupied_seats',
        ),
        migrations.RemoveField(
            model_name='restauranttable',
            name='seats',
        ),
    ]
