# Generated by Django 5.2.8 on 2025-11-20 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_restauranttable_seats_per_row_and_more'),
        ('management', '0009_remove_restauranttable_occupied_seats_and_more'),
    ]

    operations = [
    ]
